baseURL: "https://padelup-hugo-bulma.pages.dev"
languageCode: "it"
title: "Padel Up"
logo: "/images/logo/padelup.svg"

social:
  facebook: "padelup.it"
  facebook_admin: "105017614585389"

googleAnalytics: G-DH355JDJPH

# Open Graph
params:
  description: "Il padel a tutto un altro livello. Recensioni, guide, news e approfondimenti sul mondo del paddle."
  images: 
    - /images/logo/padelup.png
  title: "Padel Up"

summaryLength: 10
paginate: 6

